### ISSUE TITLE
hi how to use the code?

### ISSUE THREAD

**Issue by Luo-Yihong** [OdinTech3/IP-Visualizer#1]
Could you tell me how to use the code?

**Comment by nicksspirit** [comment]
Are you familiar with integer programming?

**Comment by Luo-Yihong** [comment]
yes, but I don't konw how to use the code...

**Comment by nicksspirit** [comment]
Okay so I am assuming you are using RStudio:

You first have to make sure you have the following R package dependencies

- lpSolveAPI
- igraph

Then you need to define the integer programming problem you want to solve and visualize, look at lines [L45-L49](https://github.com/OdinTech3/IP-Visualizer/blob/9378c8c7af692ea04ec7b91b9e82db8710beb0a7/branch_bound.r#L45-L49)

```
ip_prob <- make.lp(0, 2) %T>%
  lp.control(sense = "max") %T>%
  set.objfn(c(8, 5)) %T>%
  add.constraint(c(1, 1), "<=", 6) %T>%
  add.constraint(c(9, 5), "<=", 45)
```

You need to change the objective function and constraints to match the integer programming problem you are are trying to solve, then run the script branch_bound.r it should output a png with the solution.

Do you have an example integer programming problem you want to solve?
